name: MR-develop

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  docs:
    name: 'Build Docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://github.com/swaggo/swag/releases/download/v1.7.4/swag_1.7.4_Linux_x86_64.tar.gz
          tar -zxvf swag_1.7.4_Linux_x86_64.tar.gz
      - run: ./swag init -g cmd/app/main.go
      - uses: actions/upload-artifact@v3
        with:
          name: docs-dist
          path: ./docs/**

  run-tests:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true

      - name: get deps
        run: go mod download

      - name: fetch numary control
        uses: actions/download-artifact@v3
        with:
          name: docs-dist
          path: docs/

      - name: Run test
        run: go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...


  run-buld:
    name: 'Run test build app'
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true

      - name: get deps
        run: go mod download

      - name: fetch numary control
        uses: actions/download-artifact@v3
        with:
          name: docs-dist
          path: docs/

      - name: test build
        run: go build cmd/app/main.go