# This is a basic workflow to help you get started with Actions

name: Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    name: 'Build Docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://github.com/swaggo/swag/releases/download/v1.7.4/swag_1.7.4_Linux_x86_64.tar.gz
          tar -zxvf swag_1.7.4_Linux_x86_64.tar.gz
      - run: ./swag init -g cmd/app/main.go
      - uses: actions/upload-artifact@v3
        with:
          name: docs-dist
          path: ./docs/**

  run-tests:
    name: 'Run Tests'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs:
      - docs
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true

      - name: get deps
        run: go mod download

      - name: fetch numary control
        uses: actions/download-artifact@v3
        with:
          name: control-dist
          path: cmd/control/

      - name: Run test
        run: go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...

      - name: test build
        run: go build
