name: Staging

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  docs:
    name: 'Build Docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://github.com/swaggo/swag/releases/download/v1.7.4/swag_1.7.4_Linux_x86_64.tar.gz
          tar -zxvf swag_1.7.4_Linux_x86_64.tar.gz
      - run: ./swag init -g cmd/app/main.go
      - uses: actions/upload-artifact@v3
        with:
          name: docs-dist
          path: ./docs/**

  run-tests:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true

      - name: get deps
        run: go mod download

      - name: fetch numary control
        uses: actions/download-artifact@v3
        with:
          name: docs-dist
          path: docs/

      - name: Run test
        run: go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...

  build-image:
    name: 'Build and push docker image'
    runs-on: ubuntu-latest
    needs:
      - docs
      - run-tests
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: fetch numary control
        uses: actions/download-artifact@v3
        with:
          name: docs-dist
          path: docs/

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: emil11078/thing-repository:latest
          secrets: |
            SALT=${{ secrets.SALT }}
            TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}

  deploy:
    name: 'Deploy to server'
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - name: deploy to raspberry
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_PI_SSH_HOST }}
          username: ${{ secrets.RASPBERRY_PI_USERNAME }}
          password: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          script: |
            cd thing-repository
            sudo docker pull emil11078/thing-repository:latest
            sudo docker-compose restart